#GET http://localhost:8080/adventure-lab/adventure-id-by-smart-link/gpsmazeuk2016
#GET http://localhost:8080/adventure-lab/adventure-id-by-smart-link/HistoricHomes
GET http://localhost:8080/adventure-lab/adventure-id-by-smart-link/1acfdcdd-9a2a-4e23-b17f-f44d6c2ced4d
